name: Cinefy Full CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Backend ----------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend
        working-directory: cinefy-backend
        run: mvn clean package -DskipTests

      # ---------- Frontend ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: cinefy-frontend
        run: npm install

      - name: Build Frontend
        working-directory: cinefy-frontend
        run: npm run build

      # ---------- Docker ----------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cinefy-backend ./cinefy-backend

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cinefy-frontend ./cinefy-frontend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cinefy-backend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cinefy-frontend